### ISSUE TITLE
Animation is glitching

### ISSUE THREAD

**Issue by pasyuk** [michaelrafailyk/stickymate#12] opened 2022-02-08 19:09 UTC
Animation is glitching when there is -100vh:{...}, 0: {}, 100vh: {}
but element is already visible on the page on load.

**Comment by rafailyk** [comment] 2022-02-08 21:55
Hi! Can you provide a live sample where the issue happens?

**Comment by pasyuk** [comment] 2022-02-08 22:02
I've already fixed it adding condition `position = (0 > position) ? 0 : Math.round(position);`, so now position can't be < 0

`
        // convert keys to pixels and get sorted keys
	keys:
	for (let key in params[property_name]) {
		let position = key.split(/(-?\d*\.?\d+)/).filter(function(e) {return e === 0 || e});
		if (!position[0].match(/\d/)) continue keys;
		let numbers = +position[0] + 0;
		let units = position[1];
		position = convert.unitsToPixels(numbers, units) + top;
		position = (0 > position) ? 0 : Math.round(position);
		property_value[position] = params[property_name][key];
	}`

**Comment by rafailyk** [comment] 2022-02-09 10:26
@pasyuk Looks logical.
Which browser do you use to reproduce this issue?

**Comment by pasyuk** [comment] 2022-02-09 16:15
Tested on Chrome Mac OS and iPhone. Also mobile Safari. I have element with a height 120vh and on the page where it half visible onload the transform animation was glitchy. On scroll it just moved from start to end position very quickly.

**Comment by rafailyk** [comment] 2022-02-09 18:35
Don't know why but I can't reproduce that behavior on Chrome on macOS.
Anyway, I already committed your improvement to the Master.
Thank you!

**Closed** 2024-10-31 21:15 UTC
